# See https://jekyllrb.com/docs/configuration/

# Website details
lang: en
favicon: /images/favicon/favicon.ico
google-analytics: false # Put here your google analytics UA code

# Where things are
source: .
destination: ./_site
collections_dir: ./collections
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title:output_ext
  articles:
    output: true
    permalink: /articles/:year/:month/:day/:title:output_ext

# Handling Reading
safe: false
include: [".htaccess"]
exclude:
  [
    "**/README",
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: false
future: false
unpublished: true

# Plugins
whitelist: []
plugins: 
 - jekyll-tidy
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-seo-tag

# jekyll_tidy
jekyll_tidy:
  compress_html: true 

# jekyll-sitemap
sitemap: true
defaults: # exclude files from your sitemap
  - scope:
      path: "assets/**"
    values:
      sitemap: false
  - scope:
      path: "images/**"
    values:
      sitemap: false

# jekyll-seo-tag
# check https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Website Title
tagline: "Website tagline"
description: Website description
url: "https://mywebsite.com"
logo: /images/logo.png

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
quiet: false
verbose: false
defaults: []

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
